language: node_js
node_js:
  - "node"
  - "0.12"
  - "0.10"
sudo: false

install:
  - npm install -g gulp typescript aurelia-cli
  - npm install
script:
  - gulp build-ts
  - gulp sass
  - au build --env prod
